type = "EXTENSION"
version = "0.10"

[schema]
[[schema.fields]]
name = "psc_key"
type = "Int32"
nullable = false

[decoder]
name = "rle"
description = "decode RLE (NOT vectorized)"

[data]
name = "CommonGovernment_45_rle"
description = "Any RLE encoded column of Int32 values from the CommonGovernment dataset"
count = 141_123_827

