// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)"
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

#[path = "packing.skel.rs"]
mod packing_skel;

#[path = "rle.skel.rs"]
mod rle_skel;

pub use packing_skel::*;

pub use rle_skel::*;
