type = "EXTENSION"
version = "0.8"

[schema]
[[schema.fields]]
name = "col1"
type = "Int32"
nullable = false

[decoder]
name = "rle_simd"
description = "decode RLE (vectorized)"

[data]
name = "Bimbo_Agencia_ID"
description = "Any RLE encoded column of Int32 values from the Bimbo PubliBI dataset."
count = 74_180_464

